import customerModel from '../model/customer.model.js';
import farmerModel from '../model/farmer.model.js';
import productModel from '../model/product.model.js';
import marketModel from '../model/market.model.js';
import categoryModel from '../model/category.model.js';
import orderModel from '../model/order.model.js';
import moderationModel from '../model/moderation.model.js';
import announcementModel from '../model/announcement.model.js';
import stallLocationModel from '../model/stallLocation.model.js';
import reviewModel from '../model/review.model.js';
import hashPassword from '../utilities/hashpassword.js';

export const markets = [
  {
    marketId: 'mkt-1',
    name: 'DHA & Clifton Fresh Pavilion',
    address: 'Khayaban-e-Shahbaz, Phase 6, DHA, Karachi',
    operatingDays: ['Wednesday', 'Saturday', 'Sunday'],
    timings: '07:30 AM - 02:00 PM',
    lat: 24.8015,
    lng: 67.0682,
    activeVendorsCount: 38,
    status: 'open',
  },
  {
    marketId: 'mkt-2',
    name: 'Empress Market Heritage Bazaar',
    address: 'Preedy Street, Saddar, Karachi',
    operatingDays: ['Thursday', 'Sunday'],
    timings: '08:00 AM - 01:30 PM',
    lat: 24.8615,
    lng: 67.0315,
    activeVendorsCount: 26,
    status: 'open',
  },
  {
    marketId: 'mkt-3',
    name: 'Gulshan-e-Iqbal Fresh Hub',
    address: 'University Road, Hassan Square, Karachi',
    operatingDays: ['Tuesday', 'Friday'],
    timings: '09:00 AM - 03:00 PM',
    lat: 24.9180,
    lng: 67.0971,
    activeVendorsCount: 22,
    status: 'open',
  },
  {
    marketId: 'mkt-4',
    name: 'Hydri Super Market',
    address: 'Block H, North Nazimabad, Karachi',
    operatingDays: ['Saturday', 'Sunday'],
    timings: '07:00 AM - 01:00 PM',
    lat: 24.9392,
    lng: 67.0425,
    activeVendorsCount: 19,
    status: 'open',
  },
  {
    marketId: 'mkt-5',
    name: 'Malir Organic Farm Hub',
    address: 'Main Super Highway, Malir Cantonment, Karachi',
    operatingDays: ['Sunday'],
    timings: '08:30 AM - 02:30 PM',
    lat: 24.9056,
    lng: 67.1950,
    activeVendorsCount: 15,
    status: 'seasonal',
  },
];

export const mapStalls = [
  {
    stallId: 'stl-101',
    stallNumber: 'Stall #14',
    stallName: 'Green Valley Organic Stall',
    farmerName: 'Marcus Vance',
    marketId: 'mkt-1',
    marketName: 'DHA & Clifton Fresh Pavilion',
    category: 'Veggies & Leafy Greens',
    lat: 24.8025,
    lng: 67.0690,
    rating: 4.9,
    ordersCount: 642,
    phone: '(021) 3584-8901',
    description: 'North Pavilion Lane, Booth 14. Certified organic greens, local farm carrots, and cabbage harvested fresh at 5:00 AM from Malir farms.',
    specialtyItems: ['Sindh Organic Carrots', 'Crisp Cabbage', 'Fresh Palak (Spinach)', 'Fresh Broccoli'],
    pickupWindows: ['08:00 AM - 09:30 AM', '09:30 AM - 11:00 AM', '11:00 AM - 12:30 PM'],
  },
  {
    stallId: 'stl-102',
    stallNumber: 'Stall #04',
    stallName: 'Pacific Berry & Orchard',
    farmerName: 'Elena Rostova',
    marketId: 'mkt-1',
    marketName: 'DHA & Clifton Fresh Pavilion',
    category: 'Fruits & Berries',
    lat: 24.8010,
    lng: 67.0672,
    rating: 4.8,
    ordersCount: 380,
    phone: '(021) 3584-7890',
    description: 'North Pavilion Lane, Booth 04. Farm-fresh strawberries, sweet blueberries, and stone fruit.',
    specialtyItems: ['Coastal Strawberries', 'Sweet Blueberries', 'Sindhri Mangoes'],
    pickupWindows: ['08:30 AM - 10:00 AM', '10:00 AM - 12:00 PM'],
  },
  {
    stallId: 'stl-201',
    stallNumber: 'Stall #08',
    stallName: 'Sunstone Orchard & Apiary',
    farmerName: 'Silvia Morales',
    marketId: 'mkt-2',
    marketName: 'Empress Market Heritage Bazaar',
    category: 'Fruits & Honey',
    lat: 24.8620,
    lng: 67.0320,
    rating: 4.8,
    ordersCount: 420,
    phone: '(021) 3272-9012',
    description: 'Central Hall, Stall 08. Mirpurkhas mangoes, sweet Kinnow, fresh pomegranates, and organic raw honey.',
    specialtyItems: ['Sweet Kinnow', 'Anar (Pomegranate)', 'Pure Wild Honey'],
    pickupWindows: ['08:30 AM - 10:30 AM', '10:30 AM - 01:00 PM'],
  },
  {
    stallId: 'stl-301',
    stallNumber: 'Stall #03',
    stallName: 'Heritage Root Organics',
    farmerName: 'Dale Henderson',
    marketId: 'mkt-3',
    marketName: 'Gulshan-e-Iqbal Fresh Hub',
    category: 'Root Crops & Squash',
    lat: 24.9186,
    lng: 67.0978,
    rating: 4.9,
    ordersCount: 340,
    phone: '(021) 3498-1122',
    description: 'University Road Gate, Stall 03. Sweet butternut squash, farm sweet potatoes, and organic beetroot.',
    specialtyItems: ['Sweet Potatoes', 'Red Beetroots', 'Butternut Squash'],
    pickupWindows: ['09:30 AM - 11:30 AM', '11:30 AM - 02:00 PM'],
  },
  {
    stallId: 'stl-401',
    stallNumber: 'Stall #22',
    stallName: 'Bluebell Meadow Pastures',
    farmerName: 'Clara & Jonah Bennett',
    marketId: 'mkt-4',
    marketName: 'Hydri Super Market',
    category: 'Pasture Eggs & Dairy',
    lat: 24.9398,
    lng: 67.0432,
    rating: 4.7,
    ordersCount: 512,
    phone: '(021) 3663-4411',
    description: 'Block H Entrance, Stall 22. Certified desi eggs, fresh organic milk, and cultured dahi.',
    specialtyItems: ['Desi Farm Eggs', 'Fresh Dahi', 'Organic Khoya'],
    pickupWindows: ['07:30 AM - 09:30 AM', '09:30 AM - 12:00 PM'],
  },
  {
    stallId: 'stl-501',
    stallNumber: 'Stall #05',
    stallName: 'Ridgefield Greenhouse Co.',
    farmerName: 'Arthur Pendelton',
    marketId: 'mkt-5',
    marketName: 'Malir Organic Farm Hub',
    category: 'Hydroponics & Tomatoes',
    lat: 24.9062,
    lng: 67.1958,
    rating: 4.6,
    ordersCount: 184,
    phone: '(021) 3450-2234',
    description: 'Super Highway Pavilion, Stall 05. Vine-ripened organic tomatoes and farm cucumbers directly from Malir fields.',
    specialtyItems: ['Vine Tomatoes', 'Long Cucumbers', 'Green Bell Peppers'],
    pickupWindows: ['08:30 AM - 11:00 AM', '11:00 AM - 01:30 PM'],
  },
];

export const seedDatabase = async () => {
  try {
    // Check if markets need migration to Karachi coordinates
    const karachiMarkets = await marketModel.countDocuments({ lat: { $gt: 24, $lt: 26 } });
    if (karachiMarkets === 0) {
      console.log("Migrating database markets & stalls to Karachi, Pakistan...");
      await marketModel.deleteMany({});
      await marketModel.insertMany(markets);
      await stallLocationModel.deleteMany({});
      await stallLocationModel.insertMany(mapStalls);
      console.log("Karachi markets and stalls synchronized successfully.");
    }

    const existingProducts = await productModel.countDocuments();
    if (existingProducts > 0) {
      console.log(`Database already seeded (${existingProducts} products found). Skipping duplicate product seed.`);
      return;
    }

    console.log("Seeding fresh initial dataset into AptechDB2...");

    // 1. Seed Users (Admin, Farmer, Customer)
    const adminPwd = await hashPassword('admin123');
    const farmerPwd = await hashPassword('farmer123');
    const customerPwd = await hashPassword('customer123');

    const users = [
      {
        customerNumber: 1,
        customerName: 'Eleanor Vance',
        name: 'Eleanor Vance',
        email: 'admin@marketlink.org',
        pwd: adminPwd,
        file: 'admin123',
        role: 'admin',
        phone: '(555) 019-2831',
        addressLine1: 'Central Platform Operations',
        address: 'Central Platform Operations',
        isEmailVerified: true,
        status: 'active',
        badge: 'System Superadmin',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      },
      {
        customerNumber: 2,
        customerName: 'Marcus Vance',
        name: 'Marcus Vance',
        email: 'marcus@greenvalleyfarms.com',
        pwd: farmerPwd,
        file: 'farmer123',
        role: 'vendor',
        phone: '(555) 234-8901',
        addressLine1: 'Green Valley Organic Stall #14, Downtown Pavilion',
        address: 'Green Valley Organic Stall #14, Downtown Pavilion',
        isEmailVerified: true,
        status: 'active',
        badge: 'Certified Organic Grower',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      },
      {
        customerNumber: 3,
        customerName: 'Clara Higgins',
        name: 'Clara Higgins',
        email: 'clara.higgins@gmail.com',
        pwd: customerPwd,
        file: 'customer123',
        role: 'customer',
        phone: '(555) 312-8874',
        addressLine1: '428 Elm Street, Apt 3B',
        address: '428 Elm Street, Apt 3B',
        isEmailVerified: true,
        status: 'active',
        totalOrders: 28,
        totalSpent: 642.50,
        badge: 'Community Patron Tier 2',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      },
      {
        customerNumber: 4,
        customerName: 'Liam Sterling',
        name: 'Liam Sterling',
        email: 'liam.sterling@outlook.com',
        pwd: customerPwd,
        file: 'customer123',
        role: 'customer',
        phone: '(555) 902-1145',
        addressLine1: '710 Pacific Blvd, Suite 101',
        address: '710 Pacific Blvd, Suite 101',
        isEmailVerified: true,
        status: 'active',
        totalOrders: 19,
        totalSpent: 485.20,
      },
    ];

    await customerModel.insertMany(users);

    // 2. Seed Farmers
    const farmers = [
      {
        farmerId: 'f-1',
        name: 'Marcus Vance',
        farmName: 'Green Valley Organic Stall',
        email: 'marcus@greenvalleyfarms.com',
        phone: '(555) 234-8901',
        location: 'Downtown Fresh Pavilion, Stall #14',
        status: 'approved',
        rating: 4.9,
        totalOrders: 642,
        revenue: 14850,
        productCount: 8,
        categories: ['Fresh Vegetables', 'Root Tubers & Potatoes'],
        operationalDays: ['Wednesday', 'Saturday', 'Sunday'],
        pickupWindows: ['08:00 AM - 09:30 AM', '09:30 AM - 11:00 AM', '11:00 AM - 12:30 PM'],
        marketId: 'mkt-1',
        marketName: 'Downtown Fresh Pavilion',
        lat: 37.7749,
        lng: -122.4194,
      },
      {
        farmerId: 'f-2',
        name: 'Silvia Morales',
        farmName: 'Sunstone Orchard & Apiary',
        email: 'silvia@sunstoneorchard.com',
        phone: '(555) 782-9012',
        location: 'Sunset Farmers Bazaar, Stall #08',
        status: 'approved',
        rating: 4.8,
        totalOrders: 420,
        revenue: 9640,
        productCount: 6,
        categories: ['Orchard & Berry Fruits'],
        operationalDays: ['Thursday', 'Sunday'],
        pickupWindows: ['08:30 AM - 10:00 AM', '10:00 AM - 12:00 PM'],
        marketId: 'mkt-2',
        marketName: 'Sunset Farmers Bazaar',
        lat: 37.7599,
        lng: -122.495,
      },
      {
        farmerId: 'f-3',
        name: 'Dale Henderson',
        farmName: 'Heritage Root Organics',
        email: 'dale@heritageroot.org',
        phone: '(555) 349-1122',
        location: 'Oakwood Organic Pavilion, Stall #03',
        status: 'pending',
        rating: 0.0,
        totalOrders: 0,
        revenue: 0,
        productCount: 4,
        categories: ['Root Tubers & Potatoes'],
      },
    ];

    await farmerModel.insertMany(farmers);

    // 3. Seed Markets
    await marketModel.insertMany(markets);

    // 4. Seed Master Categories
    const categories = [
      { categoryId: 'cat-veggies', name: 'Fresh Vegetables', itemCount: 1890, badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200', iconName: 'veggies' },
      { categoryId: 'cat-tubers', name: 'Root Tubers & Potatoes', itemCount: 2040, badgeColor: 'bg-amber-50 text-amber-700 border-amber-200', iconName: 'tubers' },
      { categoryId: 'cat-fruits', name: 'Orchard & Berry Fruits', itemCount: 680, badgeColor: 'bg-rose-50 text-rose-700 border-rose-200', iconName: 'fruits' },
      { categoryId: 'cat-fish', name: 'Wild Catch & Fishery', itemCount: 548, badgeColor: 'bg-sky-50 text-sky-700 border-sky-200', iconName: 'fish' },
      { categoryId: 'cat-dairy', name: 'Artisan Dairy & Eggs', itemCount: 320, badgeColor: 'bg-yellow-50 text-yellow-700 border-yellow-200', iconName: 'dairy' },
      { categoryId: 'cat-meat', name: 'Pasture-Raised Meats', itemCount: 236, badgeColor: 'bg-red-50 text-red-700 border-red-200', iconName: 'meat' },
    ];

    await categoryModel.insertMany(categories);

    // 5. Seed Products (Covers all 4 dimensions: Farmer, Category, Price, Area)
    const products = [
      {
        productID: 1,
        productName: 'Savoy Crisp Cabbage',
        name: 'Savoy Crisp Cabbage',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'Marcus Vance',
        farmerName: 'Marcus Vance',
        farmName: 'Green Valley Organic Stall #14',
        buyPrice: 4.80,
        price: 4.80,
        quantityInStock: 145,
        stock: 145,
        unit: 'head',
        image: 'Aptech-1.jpg',
        imageType: 'cabbage',
        area: 'Downtown Metro',
        marketName: 'Downtown Fresh Pavilion',
        farmerRating: 4.9,
        productDescription: 'Crinkled sweet leaves grown in rich organic compost. Harvested daily before dawn.',
        description: 'Crinkled sweet leaves grown in rich organic compost. Harvested daily before dawn.',
      },
      {
        productID: 2,
        productName: 'Tuscan Lacinato Kale',
        name: 'Tuscan Lacinato Kale',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'Marcus Vance',
        farmerName: 'Marcus Vance',
        farmName: 'Green Valley Organic Stall #14',
        buyPrice: 3.50,
        price: 3.50,
        quantityInStock: 84,
        stock: 84,
        unit: 'bunch',
        image: 'Aptech-2.jpg',
        imageType: 'kale',
        area: 'Downtown Metro',
        marketName: 'Downtown Fresh Pavilion',
        farmerRating: 4.9,
        productDescription: 'Deep blue-green Italian dinosaur kale, tender and nutrient dense.',
        description: 'Deep blue-green Italian dinosaur kale, tender and nutrient dense.',
      },
      {
        productID: 3,
        productName: 'Crown Fresh Broccoli',
        name: 'Crown Fresh Broccoli',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'Marcus Vance',
        farmerName: 'Marcus Vance',
        farmName: 'Green Valley Organic Stall #14',
        buyPrice: 3.90,
        price: 3.90,
        quantityInStock: 112,
        stock: 112,
        unit: 'kg',
        image: 'Aptech-4.jpg',
        imageType: 'broccoli',
        area: 'Downtown Metro',
        marketName: 'Downtown Fresh Pavilion',
        farmerRating: 4.8,
        productDescription: 'Tight emerald florets packed with antioxidants. Crisp and sweet.',
        description: 'Tight emerald florets packed with antioxidants. Crisp and sweet.',
      },
      {
        productID: 4,
        productName: 'Crisp Organic Celery',
        name: 'Crisp Organic Celery',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'Marcus Vance',
        farmerName: 'Marcus Vance',
        farmName: 'Green Valley Organic Stall #14',
        buyPrice: 2.80,
        price: 2.80,
        quantityInStock: 95,
        stock: 95,
        unit: 'bunch',
        image: 'Aptech-1.jpg',
        imageType: 'celery',
        area: 'Downtown Metro',
        marketName: 'Downtown Fresh Pavilion',
        farmerRating: 4.7,
        productDescription: 'Snap-crisp heirloom Pascal celery with aromatic tender leafy tops.',
        description: 'Snap-crisp heirloom Pascal celery with aromatic tender leafy tops.',
      },
      {
        productID: 5,
        productName: 'Organic Heirloom Carrots',
        name: 'Organic Heirloom Carrots',
        productLine: 'Root Tubers & Potatoes',
        category: 'Root Tubers & Potatoes',
        productVendor: 'Marcus Vance',
        farmerName: 'Marcus Vance',
        farmName: 'Green Valley Organic Stall #14',
        buyPrice: 3.45,
        price: 3.45,
        quantityInStock: 230,
        stock: 230,
        unit: 'kg',
        image: 'Aptech-2.jpg',
        imageType: 'carrot',
        area: 'North Valley',
        marketName: 'Downtown Fresh Pavilion',
        farmerRating: 5.0,
        productDescription: 'Rainbow heirloom carrots harvested at 5 AM with fresh green tops intact.',
        description: 'Rainbow heirloom carrots harvested at 5 AM with fresh green tops intact.',
      },
      {
        productID: 6,
        productName: 'Vine Ripe Heirloom Tomatoes',
        name: 'Vine Ripe Heirloom Tomatoes',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'Silvia Morales',
        farmerName: 'Silvia Morales',
        farmName: 'Sunstone Orchard & Apiary',
        buyPrice: 4.20,
        price: 4.20,
        quantityInStock: 160,
        stock: 160,
        unit: 'kg',
        image: 'Aptech-4.jpg',
        imageType: 'tomato',
        area: 'Sunset District',
        marketName: 'Sunset Farmers Bazaar',
        farmerRating: 4.8,
        productDescription: 'Sun-warmed organic tomatoes with balanced natural acidity and sweetness.',
        description: 'Sun-warmed organic tomatoes with balanced natural acidity and sweetness.',
      },
      {
        productID: 7,
        productName: 'Tri-Color Bell Peppers',
        name: 'Tri-Color Bell Peppers',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'Silvia Morales',
        farmerName: 'Silvia Morales',
        farmName: 'Sunstone Orchard & Apiary',
        buyPrice: 4.50,
        price: 4.50,
        quantityInStock: 78,
        stock: 78,
        unit: 'kg',
        image: 'Aptech-1.jpg',
        imageType: 'pepper',
        area: 'Sunset District',
        marketName: 'Sunset Farmers Bazaar',
        farmerRating: 4.8,
        productDescription: 'Crisp red, yellow, and green sweet bell peppers grown in composted loam.',
        description: 'Crisp red, yellow, and green sweet bell peppers grown in composted loam.',
      },
      {
        productID: 8,
        productName: 'White Button Mushrooms',
        name: 'White Button Mushrooms',
        productLine: 'Fresh Vegetables',
        category: 'Fresh Vegetables',
        productVendor: 'David Chen',
        farmerName: 'David Chen',
        farmName: 'Chen Mycological Farms',
        buyPrice: 5.50,
        price: 5.50,
        quantityInStock: 45,
        stock: 45,
        unit: 'box',
        image: 'Aptech-2.jpg',
        imageType: 'mushroom',
        area: 'Bayview Coast',
        marketName: 'Harbor Fresh Wharf Market',
        farmerRating: 4.9,
        productDescription: 'Locally cultivated organic culinary mushrooms in recycled pulp punnets.',
        description: 'Locally cultivated organic culinary mushrooms in recycled pulp punnets.',
      },
      {
        productID: 9,
        productName: 'Wildflower Raw Honey (500g)',
        name: 'Wildflower Raw Honey (500g)',
        productLine: 'Orchard & Berry Fruits',
        category: 'Orchard & Berry Fruits',
        productVendor: 'Silvia Morales',
        farmerName: 'Silvia Morales',
        farmName: 'Sunstone Orchard & Apiary',
        buyPrice: 11.00,
        price: 11.00,
        quantityInStock: 65,
        stock: 65,
        unit: 'jar',
        image: 'Aptech-4.jpg',
        imageType: 'carrot',
        area: 'Sunset District',
        marketName: 'Sunset Farmers Bazaar',
        farmerRating: 5.0,
        productDescription: 'Unfiltered golden wildflower honey extracted straight from seasonal beehives.',
        description: 'Unfiltered golden wildflower honey extracted straight from seasonal beehives.',
      },
      {
        productID: 10,
        productName: 'Crisp Honeycrisp Apples',
        name: 'Crisp Honeycrisp Apples',
        productLine: 'Orchard & Berry Fruits',
        category: 'Orchard & Berry Fruits',
        productVendor: 'Silvia Morales',
        farmerName: 'Silvia Morales',
        farmName: 'Sunstone Orchard & Apiary',
        buyPrice: 3.25,
        price: 3.25,
        quantityInStock: 190,
        stock: 190,
        unit: 'kg',
        image: 'Aptech-1.jpg',
        imageType: 'tomato',
        area: 'Sunset District',
        marketName: 'Sunset Farmers Bazaar',
        farmerRating: 4.9,
        productDescription: 'Hand-picked crisp Honeycrisp apples with explosive sweetness and juice.',
        description: 'Hand-picked crisp Honeycrisp apples with explosive sweetness and juice.',
      },
      {
        productID: 11,
        productName: 'Pasture-Raised Brown Eggs (Dozen)',
        name: 'Pasture-Raised Brown Eggs (Dozen)',
        productLine: 'Artisan Dairy & Eggs',
        category: 'Artisan Dairy & Eggs',
        productVendor: 'Clara & Jonah Bennett',
        farmerName: 'Clara & Jonah Bennett',
        farmName: 'Bluebell Meadow Pastures',
        buyPrice: 6.50,
        price: 6.50,
        quantityInStock: 80,
        stock: 80,
        unit: 'carton',
        image: 'Aptech-2.jpg',
        imageType: 'kale',
        area: 'Bayview Coast',
        marketName: 'Harbor Fresh Wharf Market',
        farmerRating: 4.8,
        productDescription: 'Rich amber yolks from free-roaming hens raised on non-GMO organic feed.',
        description: 'Rich amber yolks from free-roaming hens raised on non-GMO organic feed.',
      },
      {
        productID: 12,
        productName: 'Fresh Wild King Salmon Fillet',
        name: 'Fresh Wild King Salmon Fillet',
        productLine: 'Wild Catch & Fishery',
        category: 'Wild Catch & Fishery',
        productVendor: 'Thomas Keller',
        farmerName: 'Thomas Keller',
        farmName: 'Pacific Catch Fishery Co.',
        buyPrice: 16.50,
        price: 16.50,
        quantityInStock: 30,
        stock: 30,
        unit: 'kg',
        image: 'Aptech-4.jpg',
        imageType: 'broccoli',
        area: 'Bayview Coast',
        marketName: 'Harbor Fresh Wharf Market',
        farmerRating: 4.9,
        productDescription: 'Sustainably line-caught wild King Salmon portioned fresh daily on ice.',
        description: 'Sustainably line-caught wild King Salmon portioned fresh daily on ice.',
      },
    ];

    await productModel.insertMany(products);

    // 6. Seed Initial Orders with 6-stage delivery statuses
    const orders = [
      {
        orderNumber: 'ORD-9401',
        orderId: 'ORD-9401',
        customer: {
          name: 'Clara Higgins',
          email: 'clara.higgins@gmail.com',
          phone: '(555) 312-8874',
          address: '428 Elm Street, Apt 3B',
        },
        items: [
          { productID: 5, name: 'Organic Heirloom Carrots', price: 3.45, buyPrice: 3.45, qty: 3, quantity: 3, unit: 'kg', imageType: 'carrot' },
          { productID: 1, name: 'Savoy Crisp Cabbage', price: 4.80, buyPrice: 4.80, qty: 2, quantity: 2, unit: 'head', imageType: 'cabbage' },
          { productID: 2, name: 'Tuscan Lacinato Kale', price: 3.50, buyPrice: 3.50, qty: 1, quantity: 1, unit: 'bunch', imageType: 'kale' },
        ],
        subtotal: 23.45,
        deliveryCharge: 3.50,
        total: 26.95,
        status: 'placed',
        orderStatus: 'placed',
        paymentStatus: 'Paid',
        paymentstatus: 'Paid',
        deliveryStep: 1,
        deliveryType: 'delivery',
        deliveryAddress: '428 Elm Street, Apt 3B',
        deliveryArea: 'Downtown Metro',
        courierName: 'Mark Fresh Logistics (Driver #12)',
        courierPhone: '(555) 301-4491',
        stallName: 'Green Valley Organic Stall #14',
        marketName: 'Downtown Fresh Pavilion',
      },
      {
        orderNumber: 'ORD-9387',
        orderId: 'ORD-9387',
        customer: {
          name: 'Liam Sterling',
          email: 'liam.sterling@outlook.com',
          phone: '(555) 902-1145',
          address: '710 Pacific Blvd, Suite 101',
        },
        items: [
          { productID: 7, name: 'Tri-Color Bell Peppers', price: 4.50, buyPrice: 4.50, qty: 2, quantity: 2, unit: 'kg', imageType: 'pepper' },
          { productID: 5, name: 'Organic Heirloom Carrots', price: 3.45, buyPrice: 3.45, qty: 5, quantity: 5, unit: 'kg', imageType: 'carrot' },
        ],
        subtotal: 26.25,
        deliveryCharge: 0,
        total: 26.25,
        status: 'ready_for_pickup',
        orderStatus: 'ready_for_pickup',
        paymentStatus: 'Paid',
        paymentstatus: 'Paid',
        deliveryStep: 4,
        deliveryType: 'pickup',
        stallName: 'Green Valley Organic Stall #14',
        stallNumber: 'Stall #14',
        marketName: 'Downtown Fresh Pavilion',
      },
    ];

    await orderModel.insertMany(orders);

    // 7. Seed Moderation Items
    const moderation = [
      {
        moderationId: 'mod-1',
        type: 'review',
        targetName: 'Order #ORD-8831 (Ridgefield Greens)',
        authorName: 'Anonymous Buyer',
        reason: 'Reported for vulgar language & harassment towards stall staff',
        severity: 'high',
        contentPreview: '"These greens were disappointing and vendor refused return..."',
        status: 'pending',
      },
      {
        moderationId: 'mod-2',
        type: 'product',
        targetName: 'Wild Foraged Chanterelles ($120.00/kg)',
        authorName: 'Forest Harvest Co.',
        reason: 'Price anomaly trigger (+450% above regional average benchmark)',
        severity: 'medium',
        contentPreview: 'Listing price is 120.00 / kg. Requires certified mycologist certificate upload.',
        status: 'pending',
      },
    ];

    await moderationModel.insertMany(moderation);

    // 8. Seed Announcements
    const announcements = [
      {
        announcementId: 'ann-1',
        title: 'Autumn Harvest Weekend Operating Hours Extended',
        message: 'All Metro markets will operate an extra 60 minutes this Saturday. Pre-order pickup cutoff is updated.',
        targetAudience: 'all',
        priority: 'important',
        active: true,
      },
      {
        announcementId: 'ann-2',
        title: 'New Organic Certification Document Upload Required',
        message: 'Vendors claiming USDA Bio Organic must upload current credentials to stall profile by Oct 1.',
        targetAudience: 'vendors',
        priority: 'urgent',
        active: true,
      },
    ];

    await announcementModel.insertMany(announcements);

    // 9. Seed Interactive Map Stalls
    await stallLocationModel.insertMany(mapStalls);

    console.log("Seeding complete: AptechDB2 populated with full dataset.");
  } catch (err) {
    console.error("Seeding error:", err);
  }
};

export default seedDatabase;
